### ISSUE TITLE
[BUG] configuration file loading issue

### ISSUE THREAD

**Issue by odra** [eclipse-ibeji/freyja#77]
## Description

Some binaries are failing to load its respective configuration file when invoking the cli without ` cargo run ...`.

I have `FREYJA_HOME` set to `/etc/freyja`  and the following configuration file as well: `/etc/freyja/config/mock_digital_twin_config.default.json`.

I get the following error when running `mock-digital-twin`:

```
# /usr/local/bin/mock-digital-twin 
[2023-11-07T13:20:37Z ERROR mock_digital_twin] configuration file "/tmp/freyja/target/release/build/mock-digital-twin-cfea9f1437a26e32/out/mock_digital_twin_config.default.json" not found
thread 'main' panicked at mocks/mock_digital_twin/src/main.rs:97:6:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am also building those CLIs and copying them over to `/usr/local/bin`  and I get a similar error when I try to run other CLIs/binaries.

Am I missing something?

**Comment by wilyle** [comment]
Hi odra, thanks for letting us know about the issue.

There should be no requirement to use `cargo run`. I am able to run the mock digital twin both from `target/build` directly and from a copied location.

I noticed that it's looking for the default config in a `/tmp` location. Does this directory still exist when you run the application? Default config files will get copied to `OUT_DIR` during build (which is something that Cargo generates at build time), so the executables will need access to the build artifacts at the same path as the original build location in order to load properly. There is currently no support for default config in `$FREYJA_HOME`.

It would be good to get some feedback on your use case and how much this behavior impacts you, because it's something we've also run into when trying to do containerization for Freyja apps, so it might be valuable to have this kind of support.

**Comment by wilyle** [comment]
Hi @odra,

Do you have any updates to this issue? It would be good to know if the suggestions in my previous comment resolved the issue. I would also like to get feedback on the way that configuration works so that we can make improvements in how the configuration is used. Thank you!

**Comment by wilyle** [comment]
#156 should have fixed this problem since the default config files are no longer required. We've verified this in the software orchestration blueprint, and the setup that you described should be functional now. I'm going to go ahead and close this, please let me know if there are further issues with configuring things in Freyja.
